### ISSUE TITLE
[ETL of full HCUP datasets v0.2] 

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-extraction-loading#10]
We have received the entirety of the purchased HCUP data. To get it into our data warehouse there are several steps. 

## Action Items

- [x] Drexel-UHC/hcup-extraction-loading#11
- [x] Drexel-UHC/hcup-extraction-loading#12
- [x]  Drexel-UHC/hcup-dbt#11
- [x] Drexel-UHC/hcup-extraction-loading#16 
- [x] #22

**Comment by ran-codes** [comment]
ETL almost done. just waiting on indicators. 

But  a few thoughts/decision need to make:

- some charges tables are wide and some are long. should we pivot everything long (tidy) during ETL as opposed to DBT
- should we merge zcta-zip information during ETL as opposed to DBT
- need to upload indciators as seeds into DBT
-

**Comment by alinasmahl1** [comment]
Thoughts-

- what var would we pivot them long on? and why are some long currently? it's usually a row for each encounter right? 
- hmm good question. Can you tell me what you think the pro's/con's of each are? 
- waht exacrtly does "as seeds" mean??

**Comment by ran-codes** [comment]
_what var would we pivot them long on? and why are some long currently? it's usually a row for each encounter right?_

see #21 (discussion on wider/long CHGS tables).

---

_should we merge zcta-zip information during ETL as opposed to DBT? (Pros + cons)_

Not much difference. this should be a simple merge. I think I'll do it ETL just because the crosswalks are stored as .Rdata. we can always shift this to dbt. (this  is a really minor decision). 

---

 _waht exacrtly does "as seeds" mean??_

see #20 (re: seeds)

**Comment by ran-codes** [comment]
closing as all source and seed tables have been loaded into DBT!
